import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const { html, filename = "design" } = await req.json();
    if (!html) return NextResponse.json({ error: "no html" }, { status: 400 });

    const zip = new JSZip();
    zip.file("index.html", html);
    zip.file("README.md", `# ${filename}\n\nGenerated by Pixie Design Studio\n\nOpen index.html in your browser.\n`);

    const buf = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    return new NextResponse(buf, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${filename}.zip"`,
      },
    });
  } catch (e) {
    return NextResponse.json({ error: (e as Error).message }, { status: 500 });
  }
}
